apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pxhp1knbv-python 
  janus-idp.io/tekton: pxhp1knbv-python
  backstage.io/kubernetes-id: pxhp1knbv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pxhp1knbv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml