apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pxhp1knbv-python
  janus-idp.io/tekton: pxhp1knbv-python
  backstage.io/kubernetes-id: pxhp1knbv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pxhp1knbv-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
