apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pxhp1knbv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pxhp1knbv-python 
  name: pxhp1knbv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pxhp1knbv-python 
